[tool.poetry]
name = "python_advanced_topics"
version = "0.1.0"
description = ""
authors = ["hasanozdem1r <hasanozdemir1@trakya.edu.tr>"]

[tool.poetry.dependencies]
python = "^3.8"
dask = "^2022.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
