[tool.poetry]
name = "packages"
version = "0.1.0"
description = ""
authors = ["Hasan Ozdemir <hasanozdemir1@trakya.edu.tr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.10.0"
rich = "^13.7.1"
pendulum = "^3.0.0"
pydantic = "^2.6.4"
pandas = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
