name: general

on:
  # actual pipeline
  pull_request:
    branches: 
      - master
    types: [closed]
  # for testing purpose
  push:
    branches: [ fix/ci-cd-improve ]

jobs:
  general:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - id: checkout_repo
        name: checkout changes from repository
        uses: actions/checkout@v3

      - id: setup_python
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - id: prepare_environment
        name: set PYTHONPATH
        run: export PYTHONPATH="$PWD" >> $GITHUB_ENV

      - id: setup_poetry
        name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - id: cache_poetry
        name: Cache project dependencies
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - id: install_dependencies
        name: Install project dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - id: setup_pre_commit
        name: Run pre-commit
        run: |
          pip install pre-commit \
          pre-commit install \
          pre-commit run --all-files
